version: "3.2"

services:
  # Create broker for pub and sub data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "rabbitmq_data:/data"
    networks:
      - rabbitmq_py

networks:
  rabbitmq_py:
    driver: bridge

volumes:
  rabbitmq_data:
