version: "3.8"

services:
  broker:
    image: rabbitmq:latest
    # enable the mttq protocol
    command: '/bin/bash -c "rabbitmq-plugins enable rabbitmq_mqtt; rabbitmq-server"'
    container_name: "rabbitmq"
    ports:
      # - 5672:5672
      - 15672:15672
      - 1883:1883
    networks:
      - pubsub

  pub:
    build:
      context: .
      dockerfile: pub.Dockerfile
    container_name: "pub"
    command: "python3 pub.py"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    networks:
      - pubsub
    depends_on:
      - broker

  api:
    build: .
    # env_file:
    #   - .env
    container_name: "fastapi"
    ports:
      - "8000:8000"
    depends_on:
      - broker
    volumes:
      - .:/app
    networks:
      - pubsub

  db:
    image: postgres:12
    # build:
    #   context: .
    #   dockerfile: db.Dockerfile
    container_name: "psg"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # env_file:
    #   - .env
    ports:
      - "5432:5432"


networks:
  pubsub:
    driver: bridge
    ipam:
      driver: default
