version: "3.8"

services:
  # redis:
  #   image: "redis:alpine"
  #   container_name: "redis-broker"

  #   command: redis-server --requirepass lsd3sd

  #   ports:
  #     - "6379:6379"

  #   environment:
  #     - REDIS_REPLICATION_MODE=master

  #   networks:
  #     - pubsub

  rabbitmq:
    image: rabbitmq:latest

    container_name: "rabbitmq"
    ports:
      # - 5672:5672
      # - 15672:15672
      - 1883:1883

    networks:
      - pubsub

    command: rabbitmq-plugins enable rabbitmq_mqtt

  pub:
    build:
      context: .
      dockerfile: pub.Dockerfile
    container_name: "pub"
    stdin_open: true
    tty: true
    # ports:
    # - 5672:5672
    # - 15672:15672
    # - 1881:1883
    volumes:
      - .:/app
    networks:
      - pubsub
    depends_on:
      # - redis
      - rabbitmq

  api:
    build: .
    container_name: "fastapi"
    ports:
      - 8000:80
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - pubsub

networks:
  pubsub:
    driver: bridge
    ipam:
      driver: default
