version: "3.8"

services:
  broker:
    image: rabbitmq:latest

    command: '/bin/bash -c "rabbitmqctl add_user guest guest; rabbitmq-plugins enable rabbitmq_mqtt; rabbitmq-server"'

    container_name: "rabbitmq"
    ports:
      # - 5672:5672
      - 15672:15672
      - 1883:1883

    networks:
      - pubsub

  pub:
    build:
      context: .
      dockerfile: pub.Dockerfile
    container_name: "pub"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    networks:
      - pubsub
    depends_on:
      # - redis
      - broker

  api:
    build: .
    container_name: "fastapi"
    ports:
      - 8000:80
    depends_on:
      - broker
    volumes:
      - .:/app
    networks:
      - pubsub

networks:
  pubsub:
    driver: bridge
    ipam:
      driver: default
