# version: "3.2"

# services:
#   # Create broker for pub and sub data
#   rabbitmq:
#     image: rabbitmq:latest
#     container_name: "rabbitmq"
#     ports:
#       - 5672:5672
#       # for see the web page
#       - 15672:15672
#     volumes:
#       - "rabbitmq_data:/data"
#     networks:
#       - rabbitmq_py

#     #   depends_on:
# networks:
#   rabbitmq_py:
#     driver: bridge

# volumes:
#   rabbitmq_data:
# version: "3"

# services:
#   rabbitmq:
#     image: "rabbitmq:3-management"
#     container_name: "rabbitmq"
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#       - "1883:1883"

#     networks:
#       - rabbitmq_net

# networks:
#   rabbitmq_net:
#     driver: bridge

version: "3.2"

services:
  redis:
    image: "redis:alpine"
    container_name: "redis-broker"

    command: redis-server --requirepass lsd3sd

    ports:
      - "6379:6379"

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - pubsub

  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq"
    ports:
      # - 5672:5672
      # - 15672:15672
      - 1883:1883

    networks:
      - pubsub

  pub:
    build:
      context: .
      dockerfile: pub.Dockerfile
    container_name: "pub"
    stdin_open: true
    tty: true
    # ports:
      # - 5672:5672
      # - 15672:15672
      # - 1881:1883
    volumes:
      - .:/scripts
    networks:
      - pubsub
    depends_on:
      # - redis
      - rabbitmq

  api:
    build: .
    container_name: "fastapi"
    ports:
      - 8000:80
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - pubsub

networks:
  pubsub:
    driver: bridge
    ipam:
      driver: default
